declare const process: {
  env: {
    NEXT_PUBLIC_NODE_ENV: 'development' | 'production'
    NEXT_PUBLIC_SUPPORT_EMAIL: string
    NEXT_PUBLIC_BLOCKCHAIN_BLOCK_HASH_EXPLORER_URL: string
    NEXT_PUBLIC_BLOCKCHAIN_TRANSACTION_EXPLORER_URL: string
    NEXT_PUBLIC_APP_NAME: string
    NEXT_PUBLIC_APP_DOWNLOAD_URL: string
    NEXT_PUBLIC_SENTRY_DSN: string
    NEXT_PUBLIC_FIREBASE_API_KEY: string
    NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: string
    NEXT_PUBLIC_FIREBASE_PROJECT_ID: string
    NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: string
    NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: string
    NEXT_PUBLIC_FIREBASE_APP_ID: string
    NEXT_PUBLIC_JEST_WORKER_ID: string
  }
}
